// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSe2UT3Y21DoiYAOAwcb-n7WC5hrhTNQ',
    appId: '1:821598232663:web:8c1fdffd862fb227e98312',
    messagingSenderId: '821598232663',
    projectId: 'blogapp-5a80b',
    authDomain: 'blogapp-5a80b.firebaseapp.com',
    storageBucket: 'blogapp-5a80b.appspot.com',
    measurementId: 'G-E4H9MJ011R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5dlSY9PpFtNP_rOFA62Ncr-HIW4jOU4',
    appId: '1:821598232663:android:03d10da4ed8dc428e98312',
    messagingSenderId: '821598232663',
    projectId: 'blogapp-5a80b',
    storageBucket: 'blogapp-5a80b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxCXi3bGFp-9lMPpeCjdVAb6s6ZfvXcNU',
    appId: '1:821598232663:ios:c5a9cf193b8656e0e98312',
    messagingSenderId: '821598232663',
    projectId: 'blogapp-5a80b',
    storageBucket: 'blogapp-5a80b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxCXi3bGFp-9lMPpeCjdVAb6s6ZfvXcNU',
    appId: '1:821598232663:ios:c5a9cf193b8656e0e98312',
    messagingSenderId: '821598232663',
    projectId: 'blogapp-5a80b',
    storageBucket: 'blogapp-5a80b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFSe2UT3Y21DoiYAOAwcb-n7WC5hrhTNQ',
    appId: '1:821598232663:web:905a86ae3353ae2ee98312',
    messagingSenderId: '821598232663',
    projectId: 'blogapp-5a80b',
    authDomain: 'blogapp-5a80b.firebaseapp.com',
    storageBucket: 'blogapp-5a80b.appspot.com',
    measurementId: 'G-9GNY18FHLH',
  );

}